"""initial schema: complaints and complaint_analyses

Revision ID: 7b750781c031
Revises: 
Create Date: 2026-07-25 20:00:14.223286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b750781c031'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_source', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_strength_grade', sa.String(), nullable=True),
    sa.Column('batch_lot_number', sa.String(), nullable=True),
    sa.Column('manufacturing_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('quantity_affected', sa.String(), nullable=True),
    sa.Column('complaint_type', sa.String(), nullable=True),
    sa.Column('complaint_date', sa.String(), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_level'), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending_triage', 'saved', 'under_review', 'closed', name='complaint_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_batch_lot_number'), 'complaints', ['batch_lot_number'], unique=False)
    op.create_index('ix_complaints_product_batch', 'complaints', ['product_name', 'batch_lot_number'], unique=False)
    op.create_index(op.f('ix_complaints_product_name'), 'complaints', ['product_name'], unique=False)
    op.create_table('complaint_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_rationale', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Integer(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('root_cause_suggestion', sa.Text(), nullable=True),
    sa.Column('capa_suggestion', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_analyses_complaint_id'), 'complaint_analyses', ['complaint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_analyses_complaint_id'), table_name='complaint_analyses')
    op.drop_table('complaint_analyses')
    op.drop_index(op.f('ix_complaints_product_name'), table_name='complaints')
    op.drop_index('ix_complaints_product_batch', table_name='complaints')
    op.drop_index(op.f('ix_complaints_batch_lot_number'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
